### ISSUE TITLE
Wrong module name ref in import

### ISSUE THREAD

**Issue by jam-odoo** [johnwarne-gt-misports/misports-addons#1]
https://github.com/johnwarne-gt-misports/misports-addons/blob/74bff0793fb3c522ff67366d5121afd8ac3a65b3/woo_extended_misport_ept/models/woo_product_ept.py#L3

Wrong module ref :
This module model file https://github.com/johnwarne-gt-misports/misports-addons/blob/master/woo_extended_misport_ept/models/woo_product_ept.py line 3 has wrong mdoule ref
 from odoo.addons.woo_commerce_ept.img_upload import img_file_upload

should be 

 from odoo.addons.woo_commerce_v11.img_upload import img_file_upload

because you renamed the module

**Comment by johnwarne-gt-misports** [comment]
Thanks! I've made this change and the PAAS environment seems to be pulling up again. w00t!

**Comment by jam-odoo** [comment]
@johnwarne-gt-misports Glad it worked. If you renamed module then all references will also need update.
